services:
    nginx:
        image: nginx:alpine
        container_name: news-board-nginx
        restart: always
        ports:
            - "${APP_PORT:-8001}:80"
        volumes:
            - ./Docker/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www
            - news-app:/var/www
        depends_on:
            - php
        networks:
            - news-network

    php:
        build:
            args:
                user: "newsappuser"
                uid: 1000
            context: .
            dockerfile: Docker/Dockerfile
        container_name: news-board-php
        restart: always
        entrypoint: ['/usr/local/bin/entrypoint.sh']
        volumes:
            - .:/var/www
            - news-app:/var/www
        depends_on:
            - db
        networks:
            - news-network

    db:
        image: postgres:latest
        container_name: news-board-postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME:-news_app}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            POSTGRES_DB: ${DB_DATABASE:-news_app}
        volumes:
            - news-postgres-data:/var/lib/postgresql/data
        networks:
            - news-network

    cache:
        image: redis:latest
        container_name: news-board-redis
        restart: always
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
        networks:
            - news-network

networks:
    news-network:
        driver: bridge

volumes:
    news-app:
    news-postgres-data:
    cache:
